### ISSUE TITLE
Support for additional GitHub alerts

### ISSUE THREAD

**Issue by froi** [wallpants/pantsdown#179]
Hello 👋🏼 

Great project, I found it using [github-preview.nvim](https://github.com/wallpants/github-preview.nvim).

I noticed that there's two alerts not directly supported here: TIP and CAUTION. It'd be great if this was added. I'm happy to take a stab at a PR if you are accepting them.

My thought was to add Caution and Tip to [these variants](https://github.com/wallpants/pantsdown/blob/main/src/types.ts#L32) and add the icon from [octicons](https://github.com/primer/octicons/tree/main) to the [icons export](https://github.com/wallpants/pantsdown/blob/main/src/utils.ts#L284).

No worries if you're not accepting PRs now and looking forward to see these projects grow.

**Comment by wallpants** [comment]
Hey there! Thanks for checking out the project and for the kind words.

I'd definitely welcome a PR to add support for TIP and CAUTION alerts. I'd rather not add new dependencies to the project, so if we could get the icons in without adding a dependency that'd be great.

[demo](https://github.com/wallpants/pantsdown/blob/3814ef3ddf001fcfd66ede6b7163885ee5114bcc/docs/features.md?plain=1#L48-L57) should also get updated to include the new alerts.

Feel free to submit a PR if you have the time and bandwidth. Any contributions are much appreciated! Just let me know if you run into any issues.

**Comment by froi** [comment]
Cool. I already have something done but would want to test it first. Might take me longer to test than do 😅 

I'll make a submission when ready.
